(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Erin Dees, created 2017-02-14."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "Grey15")
      (background-mode . dark)
      (border-color . "Grey")
      (cursor-color . "Grey")
      (foreground-color . "Grey")
      (mouse-color . "Grey"))
     ((compilation-message-face . underline)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . link)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (list-matching-lines-prefix-face . shadow)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (Info-quoted ((t (:family "courier"))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (border ((t (:background "Grey"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "#09223F" :foreground "white"))))
     (button ((t (:underline t :foreground "cyan1"))))
     (calendar-today-face ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:foreground "light sky blue"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic :foreground "sky blue"))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cperl-array-face ((t (:bold t :foreground "light salmon" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
     (cursor ((t (:background "Grey"))))
     (custom-button-face ((t (:foreground "gainsboro"))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation-face ((t (:foreground "light blue"))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (custom-group-tag-face-1 ((t (:foreground "pale turquoise" :underline t))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "light salmon"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (diary-face ((t (:foreground "red"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (ecb-default-highlight-face ((t (:background "#26425D"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "light blue"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-notice-face ((t (:foreground "light salmon"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :foreground "light blue" :weight bold))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "medium purple" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "dim gray"))))
     (eshell-ls-clutter-face ((t (:foreground "dim gray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "medium slate blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "violet"))))
     (eshell-ls-product-face ((t (:foreground "light steel blue"))))
     (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "gold"))))
     (eshell-ls-symlink-face ((t (:foreground "white"))))
     (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
     (eshell-prompt-face ((t (:bold t :foreground "light sky blue" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "aquamarine"))))
     (font-lock-comment-delimiter-face ((t (:foreground "light blue"))))
     (font-lock-comment-face ((t (:foreground "light blue"))))
     (font-lock-constant-face ((t (:foreground "pale green"))))
     (font-lock-doc-face ((t (:foreground "light sky blue"))))
     (font-lock-doc-string-face ((t (:foreground "sky blue"))))
     (font-lock-function-name-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#8090A2"))))
     (font-lock-reference-face ((t (:foreground "pale green"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "red"))))
     (font-lock-string-face ((t (:foreground "light sky blue"))))
     (font-lock-type-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "Grey15"))))
     (glyphless-char ((t (:underline t))))
     (gnus-cite-face-1 ((t (:foreground "LightSalmon"))))
     (gnus-cite-face-2 ((t (:foreground "Khaki"))))
     (gnus-cite-face-3 ((t (:foreground "Coral"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "bisque"))))
     (gnus-cite-face-7 ((t (:foreground "peru"))))
     (gnus-cite-face-8 ((t (:foreground "light coral"))))
     (gnus-cite-face-9 ((t (:foreground "plum"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1-empty-face ((t (:foreground "White"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "White" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "White"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "White" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-header-content-face ((t (:foreground "LightSkyBlue3"))))
     (gnus-header-from-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight bold))))
     (gnus-signature-face ((t (:foreground "Grey"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "Black" :foreground "Yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (gnus-summary-high-unread-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "DimGray" :slant italic))))
     (gnus-summary-low-read-face ((t (:foreground "slate gray"))))
     (gnus-summary-low-ticked-face ((t (:foreground "Pink"))))
     (gnus-summary-low-unread-face ((t (:foreground "LightGray"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "MediumAquamarine"))))
     (gnus-summary-normal-read-face ((t (:foreground "Aquamarine"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "LightSalmon"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gui-element ((t (:background "#303030" :foreground "black"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :inverse-video nil :box nil :underline t))))
     (help-argument-name ((t (:italic t :slant italic :foreground "sky blue"))))
     (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
     (highline-face ((t (:background "DeepSkyBlue4"))))
     (hl-line ((t (:background "#00162A"))))
     (holiday-face ((t (:background "pink"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Red"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "#42D915"))))
     (ido-subdir ((t (:foreground "#008AFF"))))
     (ido-virtual ((t (:foreground "aquamarine"))))
     (info-header-node ((t (:italic t :bold t :slant italic :foreground "white" :weight bold))))
     (info-header-xref ((t (:bold t :underline t :foreground "sky blue" :weight bold))))
     (info-index-match ((t (:background "RoyalBlue3"))))
     (info-menu-header ((t (:bold t :underline t :weight bold :family "helv"))))
     (info-menu-star ((t (:foreground "red1" :underline t))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold :height 1.728 :family "helv"))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold :height 1.44 :family "helv"))))
     (info-title-3 ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (info-title-4 ((t (:bold t :weight bold :family "helv"))))
     (info-xref ((t (:bold t :underline t :foreground "sky blue" :weight bold))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "slate blue" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :foreground "sky blue" :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (linum ((t (:background "#111111" :foreground "#888888" :underline nil))))
     (mac-ts-caret-position ((t (nil))))
     (mac-ts-converted-text ((t (:underline "gray20"))))
     (mac-ts-raw-text ((t (:underline t))))
     (mac-ts-selected-converted-text ((t (:underline t))))
     (makefile-space-face ((t (:background "hotpink"))))
     (markdown-blockquote-face ((t (:foreground "light sky blue"))))
     (markdown-bold-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (markdown-comment-face ((t (:foreground "light blue"))))
     (markdown-footnote-face ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (markdown-header-delimiter-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (markdown-header-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (markdown-header-face-1 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (markdown-header-face-2 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (markdown-header-face-3 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (markdown-header-face-4 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (markdown-header-face-5 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (markdown-header-face-6 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (markdown-header-rule-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (markdown-inline-code-face ((t (:foreground "pale green"))))
     (markdown-italic-face ((t (:italic t :bold t :weight bold :foreground "turquoise" :slant italic))))
     (markdown-language-keyword-face ((t (:bold t :weight bold :foreground "sky blue"))))
     (markdown-line-break-face ((t (:foreground "pale green" :underline t))))
     (markdown-link-face ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (markdown-link-title-face ((t (:foreground "light blue"))))
     (markdown-list-face ((t (:foreground "aquamarine"))))
     (markdown-math-face ((t (:foreground "light sky blue"))))
     (markdown-metadata-key-face ((t (:bold t :weight bold :foreground "turquoise"))))
     (markdown-metadata-value-face ((t (:foreground "light sky blue"))))
     (markdown-missing-link-face ((t (:bold t :weight bold :foreground "Red"))))
     (markdown-pre-face ((t (:foreground "pale green"))))
     (markdown-reference-face ((t (:bold t :weight bold :foreground "sky blue"))))
     (markdown-url-face ((t (:foreground "light sky blue"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:foreground "MidnightBlue" :background "Grey"))))
     (message-cited-text-face ((t (:foreground "LightSalmon"))))
     (message-header-cc-face ((t (:foreground "light cyan"))))
     (message-header-name-face ((t (:foreground "LightBlue"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "MediumAquamarine"))))
     (message-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-xheader-face ((t (:foreground "MediumAquamarine"))))
     (message-mml-face ((t (:foreground "ForestGreen"))))
     (message-separator-face ((t (:foreground "chocolate"))))
     (minibuffer-prompt ((t (:foreground "#008AFF"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#222222" :foreground "#888888" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline ((t (:background "#111111" :foreground "#888888"))))
     (mouse ((t (:background "Grey"))))
     (mumamo-background-chunk-major ((t (nil))))
     (mumamo-background-chunk-submode1 ((t (nil))))
     (next-error ((t (:background "DarkSlateBlue"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (outline-1 ((t (:bold t :weight bold :foreground "aquamarine"))))
     (outline-2 ((t (:bold t :weight bold :foreground "turquoise"))))
     (outline-3 ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (outline-4 ((t (:foreground "light blue"))))
     (outline-5 ((t (:bold t :weight bold :foreground "sky blue"))))
     (outline-6 ((t (:foreground "pale green"))))
     (outline-7 ((t (:foreground "aquamarine"))))
     (outline-8 ((t (:foreground "light sky blue"))))
     (package-description ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :height 1))))
     (package-help-section-name ((t (:bold t :weight bold))))
     (package-name ((t (:underline t :foreground "cyan1"))))
     (package-status-avail-obso ((t (:foreground "light blue"))))
     (package-status-available ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :height 1))))
     (package-status-built-in ((t (:foreground "aquamarine"))))
     (package-status-dependency ((t (:foreground "light blue"))))
     (package-status-disabled ((t (:bold t :weight bold :foreground "Red"))))
     (package-status-external ((t (:foreground "aquamarine"))))
     (package-status-held ((t (:foreground "pale green"))))
     (package-status-incompat ((t (:foreground "light blue"))))
     (package-status-installed ((t (:foreground "light blue"))))
     (package-status-new ((t (:bold t :weight bold))))
     (package-status-unsigned ((t (:bold t :weight bold :foreground "Red"))))
     (query-replace ((t (:foreground "brown4" :background "slate blue"))))
     (region ((t (:background "DarkSlateBlue"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "steel blue"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "#26425D"))))
     (show-paren-match-face ((t (:background "light slate blue" :foreground "white"))))
     (show-paren-mismatch ((t (:background "#FF0000" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "red" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "seashell2"))))
     (speedbar-directory-face ((t (:foreground "seashell3"))))
     (speedbar-file-face ((t (:foreground "seashell4"))))
     (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
     (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "antique white"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "helv" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-conflict-state ((t (nil))))
     (vc-edited-state ((t (nil))))
     (vc-locally-added-state ((t (nil))))
     (vc-locked-state ((t (nil))))
     (vc-missing-state ((t (nil))))
     (vc-needs-update-state ((t (nil))))
     (vc-removed-state ((t (nil))))
     (vc-state-base ((t (nil))))
     (vc-up-to-date-state ((t (nil))))
     (vertical-border ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "#888888" :background "#222222"))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (whitespace-big-indent ((t (:background "red" :foreground "firebrick"))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "grey24" :foreground "darkgray"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:foreground "darkgray" :weight normal))))
     (whitespace-space ((t (:background "grey20" :foreground "darkgray"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "grey22" :foreground "darkgray"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "light blue"))))
     (widget-field ((t (:background "RoyalBlue4" :foreground "wheat"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "slate blue" :foreground "wheat"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40"))))
     (woman-bold-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (woman-italic-face ((t (:foreground "deep sky blue"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "DarkSlateBlue"))))
     (zmacs-region ((t (:background "DarkSlateBlue")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
